# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp to generate a chain with target joint density
#' @param a fixed number for beta distribution
#' @param b fixed number for beta distribution
#' @param n fixed number for binomial distribution
#' @return a binary Monte Carlo Markov Chain
#' @export
bivariate_density_c <- function(a, b, n) {
    .Call('_StatComp21075_bivariate_density_c', PACKAGE = 'StatComp21075', a, b, n)
}

